#!/usr/bin/ruby
# Ruby front-end for your compiler.
# You are free to change the language used for this script,
# but do *not* change its name.

if ARGV.length != 1
  puts "Compiler takes one argument which is the file to be compiled."
  exit 1
end

puts `java -cp bin:lib/antlr-4.4-complete.jar Compiler #{ARGV[0]}`

exit $?.exitstatus