#!/usr/bin/ruby
# Ruby front-end for your compiler.
# You are free to change the language used for this script,
# but do *not* change its name.

if ARGV.length != 1
  puts "main.Compiler takes one argument which is the file to be compiled."
  exit 1
end

output = `java -ea -cp bin:lib/antlr-4.4-complete.jar main.Compiler #{ARGV[0]}`
exit_status = $?.exitstatus

if exit_status == 0
    STDOUT.printf output
else
    STDERR.printf output
end

exit exit_status