package codegen.instructions;

public enum Ins {
    ADD, ADDS, AND, ASR, BEQ, BL, BLCS, BLEQ, BLLT, BLNE, BLVS, CMP, EOR, LDR, LDRCS, LDREQ, LDRLT, LDRNE, LDRSB, MOV,
    MOVEQ, MOVGE, MOVGT, MOVLE, MOVLT, MOVNE, ORR, POP, PUSH, RSBS, SMULL, STR, STRB, SUB, SUBS;
}
